import { Resource } from "../types";

// A flexible resource database, per Instruction 7 — add/remove/adjust
// entries here without touching UI code. A few of these are intentionally
// clearly-labeled placeholders standing in for a future vetted affiliate
// partner, so the recommendation UI and disclosure mechanics are real and
// demonstrable without fabricating a partnership with a real company.

export const RESOURCES: Resource[] = [
  {
    id: "res_pomeroy",
    name: "Pomeroy Lending",
    category: "mortgage",
    resourceType: "affiliated_professional",
    description:
      "CredABLE's mortgage lending resource — a complimentary strategy consultation for purchase, refinance, HELOC, investment property, and self-employed or complex-income financing.",
    helpsWith: ["home purchase", "refinance", "HELOC", "investment property financing", "self-employed / bank-statement financing", "mortgage readiness"],
    doesNotHelpWith: ["situations outside Pomeroy Lending's licensed states — a licensed network partner may apply instead", "legal or tax questions"],
    bestFor: "Anyone exploring mortgage strategy or ready for a real financing conversation.",
    pricing: "Free consultation",
    affiliateStatus: true,
    affiliateDisclosure: "Pomeroy Lending is CredABLE's mortgage lending partner. CredABLE may benefit from this relationship — that does not change whether or when we recommend it.",
    url: "#contact-pomeroy-lending",
    lastReviewed: "2026-01-01",
    activeStatus: true,
  },
  {
    id: "res_annualcreditreport",
    name: "AnnualCreditReport.com",
    category: "credit",
    resourceType: "informational",
    description: "The official, federally authorized source for a free copy of your credit report from all three bureaus.",
    helpsWith: ["reviewing your full credit file for free", "spotting reporting errors"],
    doesNotHelpWith: ["credit scores (reports only)", "disputing errors directly (bureaus handle that separately)"],
    bestFor: "Anyone who wants to see their actual credit file before making a plan.",
    pricing: "Free",
    affiliateStatus: false,
    url: "https://www.annualcreditreport.com",
    lastReviewed: "2026-01-01",
    activeStatus: true,
  },
  {
    id: "res_local_bank",
    name: "Your own bank or local credit union",
    category: "lending",
    resourceType: "informational",
    description: "For a straightforward HELOC or personal loan, your existing bank or a local credit union is often the lowest-cost first stop.",
    helpsWith: ["straightforward HELOC", "personal loans", "existing-relationship pricing"],
    doesNotHelpWith: ["complex income", "non-standard underwriting", "being declined elsewhere"],
    bestFor: "Simple, straightforward borrowing needs with an existing banking relationship.",
    pricing: "Varies by institution",
    affiliateStatus: false,
    url: "",
    lastReviewed: "2026-01-01",
    activeStatus: true,
  },
  {
    id: "res_nfcc",
    name: "NFCC-affiliated nonprofit credit counseling",
    category: "debt",
    resourceType: "informational",
    description: "Nonprofit, often free or low-cost credit counseling and debt management plans through the National Foundation for Credit Counseling network.",
    helpsWith: ["structured debt repayment", "budgeting support", "understanding options before settlement or bankruptcy"],
    doesNotHelpWith: ["situations that legally require bankruptcy protection", "secured debt like mortgages directly"],
    bestFor: "Debt that feels unmanageable but hasn't reached the point of needing legal restructuring.",
    pricing: "Often free or low-cost",
    affiliateStatus: false,
    url: "https://www.nfcc.org",
    lastReviewed: "2026-01-01",
    activeStatus: true,
  },
  {
    id: "res_credit_builder_example",
    name: "Secured credit-builder card (example placeholder)",
    category: "credit",
    resourceType: "financial_product",
    description:
      "A placeholder resource standing in for a future vetted secured-card partner — demonstrates how CredABLE will present a financial product recommendation, including the fit rules and disclosure.",
    helpsWith: ["thin credit files", "adding positive revolving history"],
    doesNotHelpWith: ["users who already have adequate revolving history", "users about to apply for major financing (a new account can temporarily hurt readiness)"],
    bestFor: "A thin or new credit file that needs positive history.",
    pricing: "Typically a small annual fee or refundable deposit",
    riskLevel: "Low",
    affiliateStatus: true,
    affiliateDisclosure: "Placeholder only — no real affiliate relationship exists yet. Replace with a vetted partner and real disclosure before launch.",
    url: "#",
    lastReviewed: "2026-01-01",
    activeStatus: true,
  },
  {
    id: "res_research_tool_example",
    name: "AI investment research tool (example placeholder)",
    category: "investing",
    resourceType: "software",
    description: "A placeholder standing in for a future research/screening tool partner — demonstrates the 'learn / research / practice / implement' resource categories from Instruction 7.",
    helpsWith: ["stock screening", "company research", "portfolio analysis"],
    doesNotHelpWith: ["users who only want simple, low-maintenance index investing"],
    bestFor: "Users who want to research individual investments themselves.",
    pricing: "Freemium, paid tiers vary",
    affiliateStatus: true,
    affiliateDisclosure: "Placeholder only — no real affiliate relationship exists yet.",
    url: "#",
    lastReviewed: "2026-01-01",
    activeStatus: true,
  },
  {
    id: "res_identity_protection",
    name: "Identity monitoring (bank-provided or dedicated service)",
    category: "protection",
    resourceType: "informational",
    description: "Many banks and credit cards already include free credit and identity monitoring — worth checking before paying for a dedicated service.",
    helpsWith: ["fraud alerts", "credit monitoring"],
    doesNotHelpWith: ["removing existing fraud or errors (that requires direct action with the bureaus/creditors)"],
    bestFor: "Anyone wanting an early-warning system on their credit file.",
    pricing: "Often already free through your bank",
    affiliateStatus: false,
    url: "",
    lastReviewed: "2026-01-01",
    activeStatus: true,
  },
];

export const RESOURCE_CATEGORIES = Array.from(new Set(RESOURCES.map((r) => r.category)));
